### ISSUE TITLE
where is install_manifest.txt

### ISSUE THREAD

**Issue by ixzh** [Slackadays/Clipboard#115]
Hey I was trying to uninstall an earlier version and use brew to manage the package.

However, according to the uninstall instruction, I can't locate the install_manifest.txt file. Is it sufficient to remove the /usr/local/bin/cb and clipboard?

**Comment by Slackadays** [comment]
@ixzh It's possible that the `install_manifest.txt` didn't get made in the right spot in an earlier version, but in your case, it should be just fine to remove those two files since that's everything it installs anyway. Then once you have Brew set up it's going to actually be even simpler because now there is only `/usr/local/bin/cb`.

**Comment by ixzh** [comment]
noted with thanks👍
