### ISSUE TITLE
Clipboard over Window

### ISSUE THREAD

**Issue by Gadgetroch** [Slackadays/Clipboard#127]
Hi,

Your project is great, but it would be awesome if I could find a way to use cb on other servers, without having to install it on each one.

Is it possible, for example, to superimpose the cb command on top of other windows?

Thank's

**Comment by Slackadays** [comment]
@Gadgetroch What do you mean by superimposing it over other windows? If you want to share a clipboard remotely, then that was added in 0.8.0 with OSC 52. You'll need a terminal like Kitty or Alacritty so that it works:

https://github.com/kovidgoyal/kitty
(Enable "clipboard-read" in the settings)
https://github.com/alacritty/alacritty

Then, all you need to do is install cb on the remote server, and the clipboard will transfer over like magic!

**Comment by Gadgetroch** [comment]
Good morning,

I was thinking as if I was running the cb paste command but on another window than a terminal.
Imagine I'm on my server, I type cb paste. It won't work because cb is not installed on my server.

But if I had the ability to run cb paste as if it was a keyboard shortcut, I could paste into the terminal

**Comment by Slackadays** [comment]
There currently doesn't exist a way to get cb to paste like you want, unless somebody makes a GUI wrapper around cb which can do that. Therefore, for now, you'll have to use a terminal in order to make use of cb's features.

However, there is a neat tool called `wmctrl` which can bring a window to the front using a keyboard shortcut. You could use that to move a terminal with cb in it to the front so you can quickly select something. Check out https://superuser.com/questions/16647/custom-hotkey-shortcut-to-open-bring-to-front-an-app for more

Also, for cb 0.8.1, I am planning to add a special TUI/Desktop mode where you can select any action without doing the `cb` command every time. This might be really helpful for you, but it doesn't exist yet.

**Comment by Slackadays** [comment]
@Gadgetroch It turns out that implementing this feature is going to be a huge pile of work to do in the terminal, and there's already a simpler way to do what you want. If you can set up a keybinding with `bind`, then you can use the following commands using `dmenu`:
```sh
$ cb cp "$(cb st | jq -r '.[] | if type=="array" then .[].path else if type=="object" then .path else . end end' | dmenu)"
# For copying the latest entry from any of your clipboards
$ cb cp "$(cb hs | jq -r '.[].content | if type=="array" then .[].path else if type=="object" then .path else . end end' | dmenu)"
# For copying any entry from a specific clipboard
```
This should achieve what you want without having to add anything. However, I'm planning on making a future GUI frontend to CB using a system like Flutter, so stay tuned for that.
