### ISSUE TITLE
Can we have —watch[clipboard] like in wl-paste?

### ISSUE THREAD

**Issue by l-o-l** [Slackadays/Clipboard#139]
**Is your feature request related to a problem? Please describe.**
I am using sway in the wsl on windows as a bit of fun. One problem I hit was that copy and paste doesn’t work between sway and windows (the clipboard 0, is different between the two). So a bit of cb —swap42 and I can work around this. But what I would really love, would be to have an event driven model that means if my “42” gains a new value I can cb paste it from either end. 

**Describe the solution you'd like**
I would like to be able to add to my sway config the following and have it work:
exec cb --watch cb copy1
exec cb 2 —watch cb copy

and from the wsl side be able to run
cb —watch cb copy1
cb 1 —watch cb copy

**Describe alternatives you've considered**
I’m a Linux noob; there are probably ways to do this already.

**Comment by Slackadays** [comment]
Would it be possible to change `CLIPBOARD_TMPDIR` so that the clipboard 0 is in the same place everywhere? You could get away by setting it on either side only, as it just has to point to where the other side is.

**Comment by l-o-l** [comment]
Seems to create a new folder on either side, so that neither side sees the other. E.g. cb show on sway creates /14 cb show in terminal will create /15 and so on.

**Comment by Slackadays** [comment]
What's your exact setup and settings? It's possible that it just wasn't set correctly

**Comment by l-o-l** [comment]
I’m not sure exactly what you mean (very inexperienced with Linux), but I’ll have a go at explaining. I have an Arch wsl install in windows. From the terminal provided I installed clipboard via the Aur (yay -S clipboard). I also installed sway. For the test as per the instructions, I ran “export CLIPBOARD_TMPDIR=/home/me/cb" from a terminal in sway and also in the wsl terminal. It acts as if there are two independent clipboards. Every time I run "cb" from one side or the other it generates a new folder in ~/cb/...



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Slackadays** [comment]
I think the problem here is that the reason there are two clipboards is because the Windows clipboard is in a different folder than the Arch one. So, to fix this, you'll need to make them point to the same folder somewhere. The easiest way to do this is to look at where the clipboards are stored by doing `cb info`. Then, on either Windows or Arch, you'll set `CLIPBOARD_TMPDIR` to match that folder on the other side. Note that CB automatically makes a `Clipboard` folder within whatever you set it to, and you can see this in `cb info`.

WSL might make this funky due to the way it shares folders, but whatever side you set `CLIPBOARD_TMPDIR` on, it'll need to match the directory structure of that side. For example, if the Windows side says something like `C:\Blah\Blah`, then you'll need to set the folder which is contained in Arch using that format, just because you're setting what the Windows version of CB sees.

**Comment by tirthpatel0007** [comment]
hotel management system project in c++

**Comment by Slackadays** [comment]
Planning on solving this by making a system clipboard daemon to always run, syncing with the CB clipboard every few seconds

**Comment by Slackadays** [comment]
Added in https://github.com/Slackadays/Clipboard/commit/95ddeadc453a4b707cb57afdeb15880c0bf774ed
