### ISSUE TITLE
clipboard can paste but not copy

### ISSUE THREAD

**Issue by crispinb** [Slackadays/Clipboard#34]
**Describe the bug**
`cb` appears to not copy anything itself (whether via pipe or cmdline arg) on my system. Its clipboard seems to hold only what is pasted by other means.

I am tempted to wonder if I'm misusing `cb` in some way, but I've gone through the README a couple of times.

**To Reproduce**
```
❯ cb clear
✓ Cleared the clipboard
❯ echo 'not README!' | wl-copy [ensure something's already on the clipboard]
❯ cb copy README.md
✓ Copied README.md                        
❯ cb show
• Here are the first 1 items in clipboard 0: 
▏ clipboard.txt 
❯ cat clipboard.txt
not README!

```
I get the same result via pipe, eg. `echo "something" | cb`

**Expected behavior**
In the above interactive sequence, I would have expected `cb show` to show that I had copied the file `README.txt`. It instead shows a 'clipboard.txt' file which contains whatever was already on the clipboard from other sources.

**Additional context**
This is on Fedora 37, with Gnome 43.2 and Wayland. Installed clipboard with the `install.sh` script

**Comment by Slackadays** [comment]
Clipboard is picking up on Xwayland's X11 clipboard contents and overwriting its own contents with that of X11. The reason it overwrote README.md is because Clipboard doesn't know yet that the X11 clipboard contents should be the same as its own and not do any overwriting, and that happened because Clipboard doesn't have X11 write support yet so it never sent README.md to X11. I disabled the WIP X11 reading in the latest commit https://github.com/Slackadays/Clipboard/commit/8c7c921cd8c9d746ecf59df8050ef1b4d3fab90f so you can try installing Clipboard with `install.sh` again, and this issue is something that @Davipb might want to take a look at later. Alternatively, you could download the latest release https://github.com/Slackadays/Clipboard/releases/tag/0.2.0 for a "known good" Clipboard version.

**Comment by Davipb** [comment]
Maybe we should change the installs scripts to point to the last release of Clipboard, or have a `develop` branch where code that isn't ready to ship yet lives? I feel like this kind of thing will happen again in the future as things change gradually in the codebase.

As for this issue in specific, I guess it's expected until we have full copy and paste support for X11. We could add a feature flag to disable X11 integration until it's fully ready.

**Comment by Slackadays** [comment]
I'll change the install scripts to clone the latest release and not the latest commit. It looks like many other projects like Mold and Gitea have the development done on `main` and only rely on releases to prevent problems like this.
