### ISSUE TITLE
GLIBC_2.32 not found - Windows 10, WSL 2

### ISSUE THREAD

**Issue by Hixon10** [Slackadays/Clipboard#50]
**Describe the bug**
Hello. 

I've tried to install `Clipboard` to Windows 10 WSL2 with `curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh | bash`.

My env is:
```
$ uname -r
5.10.16.3-microsoft-standard-WSL2

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"

$ cat /proc/version
Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021

$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
```

When I run `cb copy j.txt`, I got the following error:
```
$ cb copy j.txt
cb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by cb)
cb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by cb)
```

Maybe it makes sense to add some additional steps to an install script, or README, how to install it.

**Comment by Slackadays** [comment]
Unfortunately, Clipboard only supports platforms which support C++23, which Ubuntu 18.04 doesn't. If you can upgrade to Ubuntu 20.04 or 22.04, then you can install GCC 11 which does support C++23.

**Comment by Hixon10** [comment]
@Slackadays sure, thanks, sorry, I missed this.

**Comment by rambalachandran** [comment]
Ubuntu 20.04 has glib 2.31 and even after installing gcc 11 it still throws the error

**Comment by Slackadays** [comment]
@rambalachandran It looks like in your case, you may have to compile Clipboard from source as the premade builds are all for 22.04 and 20.04 is only barely supported. However, this is thankfully easy :partying_face:  since you already have gcc 11 and now you just need cmake to get it working. For X11/Wayland compatibility, also install `libx11-dev libwayland-dev wayland-scanner`.

So, your entire install command will look like:
```
sudo apt update
sudo apt install cmake libx11-dev libwayland-dev wayland-scanner
...whatever's in Manual Inatallation in the readme
```
