### ISSUE TITLE
Command line parameter to display Clipboards version

### ISSUE THREAD

**Issue by mvidal01** [Slackadays/Clipboard#56]
**Is your feature request related to a problem? Please describe.**
I dont recall what version of clipboard I have installed. Most command line tools have a way to report their version.

**Describe the solution you'd like**
Support the command line parameter -v or --version

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Slackadays** [comment]
When did you install Clipboard? It already reports the version in the help message.

**Comment by Slackadays** [comment]
I just realized that although the version is reported in the help message, the method to access it hasn't been documented. So, I just added the action `help` and the flags `-h, --help` to the readme. If you would like a different solution to this flag problem, feel free to say so.

Also, I just added the specific commit number to the help message too, so that's even better to know what specific build you're using. 😀
